[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https:; img-src 'self' https: data:; style-src 'self' 'unsafe-inline'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
